### ISSUE TITLE
please include some prebuilt packages and a download link in the readme

### ISSUE THREAD

**Issue by steverweber** [Stents-/XOutput#10]
please include some prebuilt packages and a download link in the readme.

**Comment by KrisZane** [comment]
https://github.com/Stents-/XOutput/releases
Might I suggest you go to releases and download it there?

**Comment by steverweber** [comment]
ah silly that i missed that... nevertheless im sure including that link in the readme is still worthwhile...
thanks!

**Comment by KrisZane** [comment]
No worries. Good idea, thanks for the input. :)
