### ISSUE TITLE
X360 Controller Triggers are both on same axis

### ISSUE THREAD

**Issue by Evilbaka** [Stents-/XOutput#15]
Many games do not support that.

**Comment by ericlbarrett** [comment]
This is part of the 350 Controller driver not XOutput. Basically the 360 Controller driver creates a virtual DirectInput device for backwards compatibility with DirectInput games. It combines both triggers into one axis for whatever reason. If you plug in a 360 controller and open the DirectInput device in joy.cpl you'll see it does the same thing.

**Comment by Evilbaka** [comment]
Okay no questions.
